Repository MyMomii/MyMomii-target, pull requests merged in 2023-11, with the labels that each got.

#10 [feat][#3] 메인 캘린더 화면 개발
  MyMomii/MyMomii.xcodeproj/project.pbxproj
  MyMomii/MyMomii.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MyMomii/MyMomii/UI/TargetViews/TargetCalView.swift
  MyMomii/MyMomii/UI/TargetViews/TargetCalViewController.swift
  MyMomii/MyMomii/UI/TargetViews/TargetCalViewRepresentable.swift
  MyMomii/MyMomii/Util/TextModifier.swift
Labels: ✨feature

#13 [feat][#11] 캘린더 뷰 UI 업데이트
  MyMomii/MyMomii.xcodeproj/project.pbxproj
  MyMomii/MyMomii/Authentication/AuthenticationManager.swift
  MyMomii/MyMomii/Authentication/AuthenticationUIView.swift
  MyMomii/MyMomii/Authentication/AuthenticationViewModel.swift
  MyMomii/MyMomii/Authentication/SettingView.swift
  MyMomii/MyMomii/Authentication/SignInEmailView.swift
  MyMomii/MyMomii/ContentView.swift
  MyMomii/MyMomii/Firestore/RootView.swift
  MyMomii/MyMomii/Firestore/UserManager.swift
  MyMomii/MyMomii/LoFi/imper/EditView.swift
  MyMomii/MyMomii/LoFi/imper/ImperMainView.swift
  MyMomii/MyMomii/LoFi/imper/MensInfo.swift
  MyMomii/MyMomii/LoFi/imper/MensInfoStore.swift
  MyMomii/MyMomii/MyMomiiApp.swift
  MyMomii/MyMomii/Profile/ProfileView.swift
  MyMomii/MyMomii/Profile/ProfileViewModel.swift
  MyMomii/MyMomii/UI/OnboardingViews/OnboardingCarouselView.swift
  MyMomii/MyMomii/UI/TargetViews/MensInfo.swift
  MyMomii/MyMomii/UI/TargetViews/SympView.swift
  MyMomii/MyMomii/UI/TargetViews/SympViewModel.swift
  MyMomii/MyMomii/UI/TargetViews/TargetCalView.swift
  MyMomii/MyMomii/UI/TargetViews/TargetCalViewModel.swift
  MyMomii/MyMomii/UI/TargetViews/TargetCalViewRepresentable.swift
  MyMomii/MyMomii/UI/TargetViews/TargetMainView.swift
  MyMomii/MyMomii/Util/TextModifier.swift
Labels: ✨feature

#14 [refactor][#9] setting views
  MyMomii/MyMomii.xcodeproj/project.pbxproj
  MyMomii/MyMomii/Resources/Assets.xcassets/Image/GuideLine/Contents.json
  MyMomii/MyMomii/Resources/Assets.xcassets/Image/GuideLine/iPhone14GuidingView.imageset/Contents.json
  MyMomii/MyMomii/Resources/Assets.xcassets/Image/GuideLine/iPhone14GuidingView.imageset/iPhone14GuidingView.png
  MyMomii/MyMomii/Resources/Assets.xcassets/Image/GuideLine/iPhoneSEGuidingView.imageset/Contents.json
  MyMomii/MyMomii/Resources/Assets.xcassets/Image/GuideLine/iPhoneSEGuidingView.imageset/iPhoneSEGuidingView.png
  MyMomii/MyMomii/UI/OnboardingViews/OnboardingCarouselView.swift
  MyMomii/MyMomii/UI/SettingViews/DetailTermView.swift
  MyMomii/MyMomii/UI/SettingViews/OutCheckView.swift
  MyMomii/MyMomii/UI/SettingViews/SettingGuideView.swift
  MyMomii/MyMomii/UI/SettingViews/SettingMainView.swift
  MyMomii/MyMomii/UI/SettingViews/SettingNotiView.swift
  MyMomii/MyMomii/UI/SettingViews/SettingTermView.swift
Labels: 🚧refactoring

#16 [feat][#4] firestore CRUD
  MyMomii/MyMomii/Firestore/UserManager.swift
  MyMomii/MyMomii/UI/TargetViews/SympView.swift
  MyMomii/MyMomii/UI/TargetViews/SympViewModel.swift
  MyMomii/MyMomii/UI/TargetViews/TargetCalView.swift
Labels: ✨feature

#15 [feat][#8] fcm
  MyMomii/MyMomii.xcodeproj/project.pbxproj
  MyMomii/MyMomii/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  MyMomii/MyMomii/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  MyMomii/MyMomii/UI/SettingViews/NotificationManager.swift
  MyMomii/MyMomii/UI/SettingViews/SettingMainView.swift
  MyMomii/MyMomii/UI/SettingViews/SettingNotiView.swift
  MyMomii/MyMomii/UI/TargetViews/TargetMainView.swift
Labels: ✨feature

#20 [hotfix][#19] 캘린더화면 16.0 버전 동작 및 로딩화면, 미래버튼 비활성화
  MyMomii/MyMomii.xcodeproj/project.pbxproj
  MyMomii/MyMomii/Resources/Assets.xcassets/Image/SnowMan/SMLoading.imageset/Contents.json
  MyMomii/MyMomii/Resources/Assets.xcassets/Image/SnowMan/SMLoading.imageset/SMLoading.png
  MyMomii/MyMomii/UI/TargetViews/LoadingView.swift
  MyMomii/MyMomii/UI/TargetViews/TargetCalView.swift
  MyMomii/MyMomii/UI/TargetViews/TargetMainView.swift
Labels: 🚨hotfix

#21 [hotfix][#18] 릴리즈용 코드 수정
  MyMomii/MyMomii.xcodeproj/project.pbxproj
  MyMomii/MyMomii.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MyMomii/MyMomii/UI/OnboardingViews/OnboardingCarouselView.swift
  MyMomii/MyMomii/UI/SettingViews/NotificationManager.swift
  MyMomii/MyMomii/UI/SettingViews/SettingComponents.swift
  MyMomii/MyMomii/UI/SettingViews/SettingGuideView.swift
  MyMomii/MyMomii/UI/SettingViews/SettingMainView.swift
  MyMomii/MyMomii/UI/SettingViews/SettingNotiView.swift
  MyMomii/MyMomii/UI/TargetViews/TargetCalView.swift
Labels: 🚨hotfix

#22 [chore][#11] 불필요한 투명도 조절 코드 제거 및 캘린더뷰 업데이트 부분 수정
  MyMomii/MyMomii/UI/TargetViews/LoadingView.swift
  MyMomii/MyMomii/UI/TargetViews/TargetCalView.swift
  MyMomii/MyMomii/UI/TargetViews/TargetCalViewRepresentable.swift
Labels: 🚨hotfix
